[2022-12-05T16:17:45.234+0100] {processor.py:153} INFO - Started process (PID=328516) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:17:45.235+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:17:45.236+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:17:45.236+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:17:45.317+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:17:45.315+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:17:45.318+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:17:45.338+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.109 seconds
[2022-12-05T16:18:30.689+0100] {processor.py:153} INFO - Started process (PID=328577) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:18:30.690+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:18:30.691+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:18:30.691+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:18:30.761+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:18:30.759+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:18:30.761+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:18:30.781+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.095 seconds
[2022-12-05T16:18:45.186+0100] {processor.py:153} INFO - Started process (PID=328625) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:18:45.188+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:18:45.189+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:18:45.189+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:18:45.262+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:18:45.261+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:18:45.263+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:18:45.281+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.100 seconds
[2022-12-05T16:19:01.025+0100] {processor.py:153} INFO - Started process (PID=328645) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:01.026+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:19:01.027+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:19:01.027+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:01.110+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:19:01.108+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:19:01.110+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:01.129+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.110 seconds
[2022-12-05T16:19:16.714+0100] {processor.py:153} INFO - Started process (PID=328664) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:16.715+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:19:16.716+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:19:16.716+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:16.794+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:19:16.792+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:19:16.794+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:16.813+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.104 seconds
[2022-12-05T16:19:33.949+0100] {processor.py:153} INFO - Started process (PID=328687) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:33.950+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:19:33.951+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:19:33.951+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:34.031+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:19:34.029+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:19:34.031+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:34.051+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.108 seconds
[2022-12-05T16:19:49.520+0100] {processor.py:153} INFO - Started process (PID=328716) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:49.522+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:19:49.523+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:19:49.522+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:49.608+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:19:49.606+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:19:49.608+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:19:49.627+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.112 seconds
[2022-12-05T16:20:06.347+0100] {processor.py:153} INFO - Started process (PID=328744) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:06.348+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:20:06.349+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:20:06.349+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:06.431+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:20:06.429+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:20:06.431+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:06.450+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.108 seconds
[2022-12-05T16:20:21.860+0100] {processor.py:153} INFO - Started process (PID=328762) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:21.861+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:20:21.862+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:20:21.862+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:21.930+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:20:21.928+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:20:21.930+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:21.966+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.110 seconds
[2022-12-05T16:20:38.401+0100] {processor.py:153} INFO - Started process (PID=328792) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:38.403+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:20:38.404+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:20:38.404+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:38.481+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:20:38.479+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:20:38.481+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:38.508+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.110 seconds
[2022-12-05T16:20:55.390+0100] {processor.py:153} INFO - Started process (PID=328817) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:55.391+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:20:55.392+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:20:55.392+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:55.474+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:20:55.472+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:20:55.474+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:20:55.492+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.107 seconds
[2022-12-05T16:21:10.428+0100] {processor.py:153} INFO - Started process (PID=328835) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:10.429+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:21:10.430+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:10.430+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:10.513+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:10.511+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:21:10.513+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:10.532+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.109 seconds
[2022-12-05T16:21:25.534+0100] {processor.py:153} INFO - Started process (PID=328852) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:25.536+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:21:25.537+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:25.537+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:25.617+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:25.616+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:21:25.618+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:25.636+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.106 seconds
[2022-12-05T16:21:42.365+0100] {processor.py:153} INFO - Started process (PID=328885) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:42.367+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:21:42.368+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:42.367+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:42.447+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:42.445+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:21:42.447+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:42.466+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.105 seconds
[2022-12-05T16:21:59.336+0100] {processor.py:153} INFO - Started process (PID=328906) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:59.337+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:21:59.338+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:59.338+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:59.419+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:59.418+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:21:59.420+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:21:59.439+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.107 seconds
[2022-12-05T16:22:15.012+0100] {processor.py:153} INFO - Started process (PID=328959) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:22:15.013+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:22:15.014+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:22:15.014+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:22:15.094+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:22:15.091+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:22:15.094+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:22:15.115+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.106 seconds
[2022-12-05T16:22:30.997+0100] {processor.py:153} INFO - Started process (PID=329011) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:22:30.998+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:22:30.999+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:22:30.999+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:22:31.068+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:22:31.066+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:22:31.068+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:22:31.087+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.093 seconds
[2022-12-05T16:22:47.493+0100] {processor.py:153} INFO - Started process (PID=329035) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:22:47.494+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:22:47.495+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:22:47.495+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:22:47.566+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:22:47.565+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:22:47.567+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:22:47.586+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.097 seconds
[2022-12-05T16:23:04.059+0100] {processor.py:153} INFO - Started process (PID=329083) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:04.060+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:23:04.061+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:23:04.061+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:04.132+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:23:04.130+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:23:04.132+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:04.151+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.097 seconds
[2022-12-05T16:23:20.148+0100] {processor.py:153} INFO - Started process (PID=329107) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:20.149+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:23:20.150+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:23:20.150+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:20.226+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:23:20.224+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:23:20.227+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:20.249+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.106 seconds
[2022-12-05T16:23:36.661+0100] {processor.py:153} INFO - Started process (PID=329159) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:36.662+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:23:36.663+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:23:36.663+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:36.742+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:23:36.740+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:23:36.742+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:36.761+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.105 seconds
[2022-12-05T16:23:50.658+0100] {processor.py:153} INFO - Started process (PID=329178) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:50.659+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:23:50.660+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:23:50.659+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:50.740+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:23:50.738+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 7, in <module>
    from airflow.operators.jdbc_operator.JdbcOperator import JdbcOperator
ModuleNotFoundError: No module named 'airflow.operators.jdbc_operator.JdbcOperator'; 'airflow.operators.jdbc_operator' is not a package
[2022-12-05T16:23:50.740+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:23:50.759+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.105 seconds
[2022-12-05T16:24:05.516+0100] {processor.py:153} INFO - Started process (PID=329207) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:05.518+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:24:05.519+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:24:05.518+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:05.598+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:24:05.597+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 8, in <module>
    from airflow.providers.jdbc.orperators.jdbc import JdbcOperator
ModuleNotFoundError: No module named 'airflow.providers.jdbc.orperators'
[2022-12-05T16:24:05.599+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:05.617+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.106 seconds
[2022-12-05T16:24:22.358+0100] {processor.py:153} INFO - Started process (PID=329259) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:22.360+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:24:22.361+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:24:22.361+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:22.439+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:24:22.437+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 8, in <module>
    from airflow.providers.jdbc.orperators.jdbc import JdbcOperator
ModuleNotFoundError: No module named 'airflow.providers.jdbc.orperators'
[2022-12-05T16:24:22.439+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:22.459+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.106 seconds
[2022-12-05T16:24:40.109+0100] {processor.py:153} INFO - Started process (PID=329289) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:40.110+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:24:40.111+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:24:40.111+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:40.184+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:24:40.182+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 8, in <module>
    from airflow.providers.jdbc.orperators.jdbc import JdbcOperator
ModuleNotFoundError: No module named 'airflow.providers.jdbc.orperators'
[2022-12-05T16:24:40.184+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:40.204+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.099 seconds
[2022-12-05T16:24:56.375+0100] {processor.py:153} INFO - Started process (PID=329315) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:56.377+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:24:56.378+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:24:56.377+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:56.461+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:24:56.459+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 8, in <module>
    from airflow.providers.jdbc.orperators.jdbc import JdbcOperator
ModuleNotFoundError: No module named 'airflow.providers.jdbc.orperators'
[2022-12-05T16:24:56.461+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:24:56.479+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.109 seconds
[2022-12-05T16:25:10.738+0100] {processor.py:153} INFO - Started process (PID=329338) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:25:10.739+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:25:10.740+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:10.740+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:25:10.817+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:10.815+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 8, in <module>
    from airflow.providers.jdbc.orperators.jdbc import JdbcOperator
ModuleNotFoundError: No module named 'airflow.providers.jdbc.orperators'
[2022-12-05T16:25:10.817+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:25:10.837+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.104 seconds
[2022-12-05T16:25:25.886+0100] {processor.py:153} INFO - Started process (PID=329356) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:25:25.888+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:25:25.888+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:25.888+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:25:25.963+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:25.961+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 8, in <module>
    from airflow.providers.jdbc.orperators.jdbc import JdbcOperator
ModuleNotFoundError: No module named 'airflow.providers.jdbc.orperators'
[2022-12-05T16:25:25.963+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:25:25.984+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.112 seconds
[2022-12-05T16:25:44.827+0100] {processor.py:153} INFO - Started process (PID=329390) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:25:44.829+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:25:44.829+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:44.829+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:25:44.903+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:44.902+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 8, in <module>
    from airflow.providers.jdbc.orperators.jdbc import JdbcOperator
ModuleNotFoundError: No module named 'airflow.providers.jdbc.orperators'
[2022-12-05T16:25:44.903+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:25:44.922+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.099 seconds
[2022-12-05T16:26:03.295+0100] {processor.py:153} INFO - Started process (PID=329416) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:03.296+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:26:03.297+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:03.297+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:03.372+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:26:03.382+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:03.510+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:03.510+0100] {manager.py:504} INFO - Created Permission View: can delete on DAG:sursaut_covid
[2022-12-05T16:26:03.521+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:03.520+0100] {manager.py:504} INFO - Created Permission View: can edit on DAG:sursaut_covid
[2022-12-05T16:26:03.528+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:03.528+0100] {manager.py:504} INFO - Created Permission View: can read on DAG:sursaut_covid
[2022-12-05T16:26:03.529+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:03.529+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:26:03.543+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:03.543+0100] {dag.py:2697} INFO - Creating ORM DAG for sursaut_covid
[2022-12-05T16:26:03.556+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:03.556+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:26:03.577+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.286 seconds
[2022-12-05T16:26:18.979+0100] {processor.py:153} INFO - Started process (PID=329434) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:18.981+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:26:18.981+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:18.981+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:19.066+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:26:19.077+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:19.103+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:19.103+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:26:19.133+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:19.133+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:26:19.156+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.182 seconds
[2022-12-05T16:26:37.031+0100] {processor.py:153} INFO - Started process (PID=329459) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:37.032+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:26:37.033+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:37.033+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:37.114+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:26:37.126+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:37.168+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:37.167+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:26:37.199+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:37.199+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:26:37.224+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.198 seconds
[2022-12-05T16:26:54.904+0100] {processor.py:153} INFO - Started process (PID=329480) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:54.905+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:26:54.906+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:54.906+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:54.982+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:26:54.992+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:26:55.028+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:55.027+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:26:55.054+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:55.054+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:26:55.075+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.177 seconds
[2022-12-05T16:27:13.491+0100] {processor.py:153} INFO - Started process (PID=329505) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:27:13.492+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:27:13.493+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:13.493+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:27:13.571+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:27:13.581+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:27:13.618+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:13.618+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:27:13.644+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:13.644+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:27:13.669+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.181 seconds
[2022-12-05T16:27:29.491+0100] {processor.py:153} INFO - Started process (PID=329525) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:27:29.492+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:27:29.493+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:29.493+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:27:29.580+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:27:29.591+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:27:29.633+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:29.632+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:27:29.665+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:29.665+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:27:29.689+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.205 seconds
[2022-12-05T16:27:46.791+0100] {processor.py:153} INFO - Started process (PID=329545) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:27:46.793+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:27:46.794+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:46.793+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:27:46.879+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:27:46.889+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:27:46.926+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:46.925+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:27:46.951+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:46.950+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:27:46.972+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.185 seconds
[2022-12-05T16:28:02.890+0100] {processor.py:153} INFO - Started process (PID=329566) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:02.891+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:28:02.892+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:02.892+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:02.979+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:28:02.989+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:03.031+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:03.031+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:28:03.062+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:03.061+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:28:03.083+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.198 seconds
[2022-12-05T16:28:18.556+0100] {processor.py:153} INFO - Started process (PID=329588) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:18.557+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:28:18.558+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:18.558+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:18.635+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:28:18.645+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:18.686+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:18.685+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:28:18.711+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:18.711+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:28:18.732+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.179 seconds
[2022-12-05T16:28:34.182+0100] {processor.py:153} INFO - Started process (PID=329693) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:34.183+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:28:34.186+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:34.185+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:34.293+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:28:34.306+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:34.380+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:34.379+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:28:34.419+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:34.419+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:28:34.474+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.299 seconds
[2022-12-05T16:28:51.201+0100] {processor.py:153} INFO - Started process (PID=329721) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:51.203+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:28:51.204+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:51.203+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:51.294+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:28:51.304+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:28:51.341+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:51.340+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:28:51.366+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:51.366+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:28:51.387+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.190 seconds
[2022-12-05T16:29:08.868+0100] {processor.py:153} INFO - Started process (PID=329738) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:08.869+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:29:08.870+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:08.869+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:08.946+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:29:08.956+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:08.993+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:08.993+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:29:09.018+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:09.018+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:29:09.041+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.177 seconds
[2022-12-05T16:29:26.236+0100] {processor.py:153} INFO - Started process (PID=329763) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:26.238+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:29:26.239+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:26.239+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:26.326+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:29:26.338+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:26.374+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:26.373+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:29:26.399+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:26.399+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:29:26.422+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.190 seconds
[2022-12-05T16:29:43.089+0100] {processor.py:153} INFO - Started process (PID=329784) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:43.091+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:29:43.092+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:43.092+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:43.181+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:29:43.193+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:43.230+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:43.230+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:29:43.257+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:43.257+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:29:43.280+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.199 seconds
[2022-12-05T16:29:58.743+0100] {processor.py:153} INFO - Started process (PID=329803) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:58.745+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:29:58.746+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:58.745+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:58.832+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:29:58.842+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:29:58.877+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:58.877+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:29:58.904+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:58.904+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:29:58.925+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.186 seconds
[2022-12-05T16:30:14.243+0100] {processor.py:153} INFO - Started process (PID=329824) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:30:14.244+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:30:14.245+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:14.245+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:30:14.330+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:30:14.344+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:30:14.381+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:14.380+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:30:14.408+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:14.407+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:30:14.429+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.189 seconds
[2022-12-05T16:30:29.804+0100] {processor.py:153} INFO - Started process (PID=329847) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:30:29.805+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:30:29.806+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:29.805+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:30:29.884+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:30:29.894+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:30:29.930+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:29.930+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:30:29.957+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:29.957+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:30:29.978+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.178 seconds
[2022-12-05T16:30:48.121+0100] {processor.py:153} INFO - Started process (PID=329869) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:30:48.122+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:30:48.123+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:48.123+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:30:48.198+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:30:48.208+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:30:48.244+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:48.244+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:30:48.269+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:48.269+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:30:48.290+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.173 seconds
[2022-12-05T16:36:03.834+0100] {processor.py:153} INFO - Started process (PID=330069) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:36:03.837+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:36:03.838+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:36:03.838+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:36:03.935+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:36:03.947+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:36:03.990+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:36:03.989+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:36:04.020+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:36:04.020+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-05T00:00:00+00:00, run_after=2022-12-06T00:00:00+00:00
[2022-12-05T16:36:04.047+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.221 seconds
[2022-12-05T16:38:32.313+0100] {processor.py:153} INFO - Started process (PID=330169) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:38:32.316+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:38:32.318+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:38:32.318+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:38:32.411+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:38:32.422+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:38:32.467+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:38:32.467+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:38:32.496+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:38:32.496+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-05T00:00:00+00:00, run_after=2022-12-06T00:00:00+00:00
[2022-12-05T16:38:32.527+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.218 seconds
[2022-12-05T16:41:03.475+0100] {processor.py:153} INFO - Started process (PID=330347) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:41:03.477+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:41:03.479+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:41:03.478+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:41:03.571+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:41:03.583+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:41:03.631+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:41:03.631+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:41:03.666+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:41:03.665+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-05T00:00:00+00:00, run_after=2022-12-06T00:00:00+00:00
[2022-12-05T16:41:03.697+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.227 seconds
[2022-12-05T16:49:08.781+0100] {processor.py:153} INFO - Started process (PID=330958) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:49:08.783+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:49:08.783+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:49:08.783+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:49:08.902+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:49:08.919+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:49:08.969+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:49:08.968+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:49:09.007+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:49:09.006+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:49:09.038+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.263 seconds
[2022-12-05T16:50:35.008+0100] {processor.py:153} INFO - Started process (PID=331034) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:50:35.016+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:50:35.017+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:50:35.017+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:50:35.138+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:50:35.152+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:50:35.193+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:50:35.193+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:50:35.223+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:50:35.222+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:50:35.252+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.248 seconds
[2022-12-05T16:57:40.273+0100] {processor.py:153} INFO - Started process (PID=331302) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:57:40.274+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:57:40.275+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:57:40.275+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:57:40.349+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:57:40.366+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:57:40.363+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 67, in <module>
    dag = Process()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 3541, in factory
    f(**f_kwargs)
  File "/home/andria/airflow/dags/sursaut_covid.py", line 64, in Process
    create_example_table() >> insert_data()
  File "/home/andria/airflow/dags/sursaut_covid.py", line 37, in create_example_table
    conn = oracle_hook.get_conn()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/providers/oracle/hooks/oracle.py", line 150, in get_conn
    conn = self.get_connection(self.oracle_conn_id)  # type: ignore[attr-defined]
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `oraclethin` isn't defined
[2022-12-05T16:57:40.366+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:57:40.378+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.108 seconds
[2022-12-05T16:58:25.887+0100] {processor.py:153} INFO - Started process (PID=331350) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:58:25.888+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:58:25.889+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:58:25.889+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:58:25.976+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:58:25.999+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:58:25.995+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 67, in <module>
    dag = Process()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 3541, in factory
    f(**f_kwargs)
  File "/home/andria/airflow/dags/sursaut_covid.py", line 64, in Process
    create_example_table() >> insert_data()
  File "/home/andria/airflow/dags/sursaut_covid.py", line 37, in create_example_table
    conn = oracle_hook.get_conn()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/providers/oracle/hooks/oracle.py", line 150, in get_conn
    conn = self.get_connection(self.oracle_conn_id)  # type: ignore[attr-defined]
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `oraclethin` isn't defined
[2022-12-05T16:58:26.000+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:58:26.018+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.136 seconds
[2022-12-05T16:58:42.348+0100] {processor.py:153} INFO - Started process (PID=331394) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:58:42.351+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:58:42.354+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:58:42.354+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:58:42.460+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:58:42.488+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:58:42.484+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 67, in <module>
    dag = Process()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 3541, in factory
    f(**f_kwargs)
  File "/home/andria/airflow/dags/sursaut_covid.py", line 64, in Process
    create_example_table() >> insert_data()
  File "/home/andria/airflow/dags/sursaut_covid.py", line 37, in create_example_table
    conn = oracle_hook.get_conn()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/providers/oracle/hooks/oracle.py", line 150, in get_conn
    conn = self.get_connection(self.oracle_conn_id)  # type: ignore[attr-defined]
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `oraclethin` isn't defined
[2022-12-05T16:58:42.489+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:58:42.505+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.161 seconds
[2022-12-05T16:58:58.372+0100] {processor.py:153} INFO - Started process (PID=331412) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:58:58.375+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:58:58.376+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:58:58.376+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:58:58.466+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:58:58.488+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:58:58.485+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 67, in <module>
    dag = Process()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 3541, in factory
    f(**f_kwargs)
  File "/home/andria/airflow/dags/sursaut_covid.py", line 64, in Process
    create_example_table() >> insert_data()
  File "/home/andria/airflow/dags/sursaut_covid.py", line 37, in create_example_table
    conn = oracle_hook.get_conn()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/providers/oracle/hooks/oracle.py", line 150, in get_conn
    conn = self.get_connection(self.oracle_conn_id)  # type: ignore[attr-defined]
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `oraclethin` isn't defined
[2022-12-05T16:58:58.489+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:58:58.503+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.135 seconds
[2022-12-05T16:59:13.141+0100] {processor.py:153} INFO - Started process (PID=331429) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:59:13.144+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:59:13.146+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:59:13.145+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:59:13.262+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:59:13.285+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:59:13.283+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 67, in <module>
    dag = Process()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 3541, in factory
    f(**f_kwargs)
  File "/home/andria/airflow/dags/sursaut_covid.py", line 64, in Process
    create_example_table() >> insert_data()
  File "/home/andria/airflow/dags/sursaut_covid.py", line 37, in create_example_table
    conn = oracle_hook.get_conn()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/providers/oracle/hooks/oracle.py", line 150, in get_conn
    conn = self.get_connection(self.oracle_conn_id)  # type: ignore[attr-defined]
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `oraclethin` isn't defined
[2022-12-05T16:59:13.286+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:59:13.303+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.171 seconds
[2022-12-05T16:59:29.636+0100] {processor.py:153} INFO - Started process (PID=331446) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:59:29.638+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:59:29.639+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:59:29.639+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:59:29.735+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:59:29.761+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:59:29.757+0100] {dagbag.py:343} ERROR - Failed to import: /home/andria/airflow/dags/sursaut_covid.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andria/airflow/dags/sursaut_covid.py", line 67, in <module>
    dag = Process()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 3541, in factory
    f(**f_kwargs)
  File "/home/andria/airflow/dags/sursaut_covid.py", line 64, in Process
    create_example_table() >> insert_data()
  File "/home/andria/airflow/dags/sursaut_covid.py", line 37, in create_example_table
    conn = oracle_hook.get_conn()
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/providers/oracle/hooks/oracle.py", line 150, in get_conn
    conn = self.get_connection(self.oracle_conn_id)  # type: ignore[attr-defined]
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `oraclethin` isn't defined
[2022-12-05T16:59:29.762+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:59:29.777+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.147 seconds
[2022-12-05T16:59:46.581+0100] {processor.py:153} INFO - Started process (PID=331473) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:59:46.582+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T16:59:46.583+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:59:46.583+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:59:46.697+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T16:59:46.714+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T16:59:46.828+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:59:46.827+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T16:59:46.853+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:59:46.853+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T16:59:46.893+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.323 seconds
[2022-12-05T17:04:40.533+0100] {processor.py:153} INFO - Started process (PID=331752) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:04:40.535+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T17:04:40.535+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:04:40.535+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:04:40.644+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T17:04:40.655+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:04:40.754+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:04:40.754+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T17:04:40.785+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:04:40.785+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid to 2022-12-05T00:00:00+00:00, run_after=2022-12-06T00:00:00+00:00
[2022-12-05T17:04:40.817+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.291 seconds
[2022-12-05T17:12:21.674+0100] {processor.py:153} INFO - Started process (PID=332051) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:12:21.677+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T17:12:21.679+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:12:21.678+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:12:21.733+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T17:12:21.749+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid_2']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:12:21.911+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:12:21.911+0100] {manager.py:504} INFO - Created Permission View: can delete on DAG:sursaut_covid_2
[2022-12-05T17:12:21.928+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:12:21.927+0100] {manager.py:504} INFO - Created Permission View: can edit on DAG:sursaut_covid_2
[2022-12-05T17:12:21.938+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:12:21.938+0100] {manager.py:504} INFO - Created Permission View: can read on DAG:sursaut_covid_2
[2022-12-05T17:12:21.939+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:12:21.939+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T17:12:21.954+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:12:21.954+0100] {dag.py:2697} INFO - Creating ORM DAG for sursaut_covid_2
[2022-12-05T17:12:21.970+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:12:21.969+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid_2 to 2022-12-04T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2022-12-05T17:12:21.996+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.327 seconds
[2022-12-05T17:13:33.911+0100] {processor.py:153} INFO - Started process (PID=332119) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:13:33.913+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T17:13:33.914+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:13:33.914+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:13:33.970+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T17:13:33.986+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid_2']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:13:34.034+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:13:34.033+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T17:13:34.065+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:13:34.064+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid_2 to 2022-12-05T00:00:00+00:00, run_after=2022-12-06T00:00:00+00:00
[2022-12-05T17:13:34.102+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.199 seconds
[2022-12-05T17:31:50.889+0100] {processor.py:153} INFO - Started process (PID=335229) to work on /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:31:50.891+0100] {processor.py:743} INFO - Processing file /home/andria/airflow/dags/sursaut_covid.py for tasks to queue
[2022-12-05T17:31:50.892+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:31:50.892+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:31:50.958+0100] {logging_mixin.py:137} WARNING - /home/andria/.local/lib/python3.10/site-packages/airflow/models/dag.py:3492 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-12-05T17:31:50.972+0100] {processor.py:753} INFO - DAG(s) dict_keys(['sursaut_covid_2']) retrieved from /home/andria/airflow/dags/sursaut_covid.py
[2022-12-05T17:31:51.031+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:31:51.030+0100] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-05T17:31:51.065+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:31:51.065+0100] {dag.py:3423} INFO - Setting next_dagrun for sursaut_covid_2 to 2022-12-05T00:00:00+00:00, run_after=2022-12-06T00:00:00+00:00
[2022-12-05T17:31:51.097+0100] {processor.py:175} INFO - Processing /home/andria/airflow/dags/sursaut_covid.py took 0.214 seconds
